imports:
    - { resource: easyadmin/ }

easy_admin:
    design:
        menu:
            -
                label: 'menu.event'
                group: 'Calendar'
                priority: 10
                children:
                    - { entity: 'Slot', icon: 'calendar-o', label: 'menu.slot' }
