imports:
    - { resource: easyadmin/ }

easy_admin:
    translation_domain: 'admin'
    design:
        menu:
            -
                label: 'menu.event'
                group: 'Calendar'
                roles: ['ROLE_CALENDAR']
                priority: 10
                children:
                    - { entity: 'Slot', icon: 'calendar-o', label: 'menu.slot' }
